# Site settings
author: Victoria Hale Williams
title: I think I can, I think I can: The little Tore that could!
header-img: img/home-bg.png
email: vic.hale74@gmail.com
copyright_name: Victoria Hale Williams
description: > # this means to ignore newlines until "baseurl:"
  She could, and she did.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  techtore

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
